# This is a basic workflow to help you get started with Actions

name: test-workflow

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      resourcegroupname:
        description: Resource Group Name
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-virtual-machine123:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 登録したシークレットで Azure へログイン
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure CLI を使用し ARM テンプレートから仮想マシンを展開
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          # {parameter file} には先の手順で作成したパラメーター ファイル名を指定
          inlineScript: |
            az deployment group create --resource-group ${{ github.event.inputs.resourceGroupName }} --template-file ./Hands-on-Lab/templates/deploy-vm-as-domain-member.json --parameters ./Hands-on-Lab/templates/deploy-vm-as-domain-member.parameters.json

      # ログアウト
      - name: Azure logout
        run: |
          az logout
